-- Auto Purchase | Jual Jeruk
-- Rayfield UI | Tycoon 1-50

local Rayfield = loadstring(game:HttpGet("https://sirius.menu/rayfield"))()

local Window = Rayfield:CreateWindow({
    Name = "Jual Jeruk | Auto Purchase",
    LoadingTitle = "Jual Jeruk Script",
    LoadingSubtitle = "by Blueprint",
    ConfigurationSaving = {
        Enabled = false,
    },
    Discord = {
        Enabled = false,
    },
    KeySystem = false,
})

local Tab = Window:CreateTab("Auto Purchase", 4483362458)

Tab:CreateButton({
    Name = "Auto Purchase (Tycoon 1-50)",
    Callback = function()
        Rayfield:Notify({
            Title = "Auto Purchase",
            Content = "Mulai beli semua item...",
            Duration = 3,
        })
        task.spawn(function()
            for i = 1, 50 do
            pcall(function() game:GetService("Workspace")["Tycoon"..i].Purchases.Hills.Buttons.Roads["Republic Road"]:InvokeServer() end)
            pcall(function() game:GetService("Workspace")["Tycoon"..i].Purchases.Hills.Buttons["Hill 2"]:InvokeServer() end)
            pcall(function() game:GetService("Workspace")["Tycoon"..i].Purchases.LemonDash.Buttons.Decor["Dash Fence"]:InvokeServer() end)
            pcall(function() game:GetService("Workspace")["Tycoon"..i].Purchases.LemonDash.Buttons.Decor["Dash Garage Door 1"]:InvokeServer() end)
            pcall(function() game:GetService("Workspace")["Tycoon"..i].Purchases.LemonDash.Buttons.Decor["Dash Garage Door 2"]:InvokeServer() end)
            pcall(function() game:GetService("Workspace")["Tycoon"..i].Purchases.LemonDash.Buttons.Decor["Dash Garage Door 3"]:InvokeServer() end)
            pcall(function() game:GetService("Workspace")["Tycoon"..i].Purchases.LemonDash.Buttons.Decor["Dash Path"]:InvokeServer() end)
            pcall(function() game:GetService("Workspace")["Tycoon"..i].Purchases.LemonDash.Buttons.Decor["Dash Roof"]:InvokeServer() end)
            pcall(function() game:GetService("Workspace")["Tycoon"..i].Purchases.LemonDash.Buttons.Decor["Dash Windows"]:InvokeServer() end)
            pcall(function() game:GetService("Workspace")["Tycoon"..i].Purchases.LemonDash.Buttons.LemonDash:InvokeServer() end)
            pcall(function() game:GetService("Workspace")["Tycoon"..i].Purchases.LemonDash.Buttons.Multiplier["Company Vehicle"]:InvokeServer() end)
            pcall(function() game:GetService("Workspace")["Tycoon"..i].Purchases.LemonDash.Buttons.Multiplier["Dash Exterior Sign"]:InvokeServer() end)
            pcall(function() game:GetService("Workspace")["Tycoon"..i].Purchases.LemonDash.Buttons.Multiplier["Influencer Collabs"]:InvokeServer() end)
            pcall(function() game:GetService("Workspace")["Tycoon"..i].Purchases.LemonDash.Buttons.Multiplier["LemonDash Plus"]:InvokeServer() end)
            pcall(function() game:GetService("Workspace")["Tycoon"..i].Purchases.LemonDash.Buttons.Multiplier["Special Deals"]:InvokeServer() end)
            pcall(function() game:GetService("Workspace")["Tycoon"..i].Purchases.LemonDash.Buttons.Structure["Dash Walls"]:InvokeServer() end)
            pcall(function() game:GetService("Workspace")["Tycoon"..i].Purchases.LemonX.Buttons.Decor["X Airlock Doors 1"]:InvokeServer() end)
            pcall(function() game:GetService("Workspace")["Tycoon"..i].Purchases.LemonX.Buttons.Decor["X Airlock Doors 2"]:InvokeServer() end)
            pcall(function() game:GetService("Workspace")["Tycoon"..i].Purchases.LemonX.Buttons.Decor["X Containers 1"]:InvokeServer() end)
            pcall(function() game:GetService("Workspace")["Tycoon"..i].Purchases.LemonX.Buttons.Decor["X Containers 3"]:InvokeServer() end)
            pcall(function() game:GetService("Workspace")["Tycoon"..i].Purchases.LemonX.Buttons.Decor["X Crate Dock 1"]:InvokeServer() end)
            pcall(function() game:GetService("Workspace")["Tycoon"..i].Purchases.LemonX.Buttons.Decor["X Crate Dock 2"]:InvokeServer() end)
            pcall(function() game:GetService("Workspace")["Tycoon"..i].Purchases.LemonX.Buttons.Decor["X Crates 3"]:InvokeServer() end)
            pcall(function() game:GetService("Workspace")["Tycoon"..i].Purchases.LemonX.Buttons.Decor["X Crates 4"]:InvokeServer() end)
            pcall(function() game:GetService("Workspace")["Tycoon"..i].Purchases.LemonX.Buttons.Decor["X Crates 5"]:InvokeServer() end)
            pcall(function() game:GetService("Workspace")["Tycoon"..i].Purchases.LemonX.Buttons.Decor["X Edge Lines"]:InvokeServer() end)
            pcall(function() game:GetService("Workspace")["Tycoon"..i].Purchases.LemonX.Buttons.Decor["X Neon Wall Trim"]:InvokeServer() end)
            pcall(function() game:GetService("Workspace")["Tycoon"..i].Purchases.LemonX.Buttons.Decor["X Rear Edge Lines"]:InvokeServer() end)
            pcall(function() game:GetService("Workspace")["Tycoon"..i].Purchases.LemonX.Buttons.Decor["X Rear Path Guide"]:InvokeServer() end)
            pcall(function() game:GetService("Workspace")["Tycoon"..i].Purchases.LemonX.Buttons.Multiplier["Agriculture Expansion"]:InvokeServer() end)
            pcall(function() game:GetService("Workspace")["Tycoon"..i].Purchases.LemonX.Buttons.Multiplier["Interdimensional Markets"]:InvokeServer() end)
            pcall(function() game:GetService("Workspace")["Tycoon"..i].Purchases.LemonX.Buttons.Multiplier["Intergalactic Lemon Trade"]:InvokeServer() end)
            pcall(function() game:GetService("Workspace")["Tycoon"..i].Purchases.LemonX.Buttons.Multiplier["Lemon Cryo Storage"]:InvokeServer() end)
            pcall(function() game:GetService("Workspace")["Tycoon"..i].Purchases.LemonX.Buttons.Multiplier["Lemon Teleportation"]:InvokeServer() end)
            pcall(function() game:GetService("Workspace")["Tycoon"..i].Purchases.LemonX.Buttons.Multiplier["Quantum Lemon Tech"]:InvokeServer() end)
            pcall(function() game:GetService("Workspace")["Tycoon"..i].Purchases.LemonX.Buttons.Multiplier["Sentient Lemons"]:InvokeServer() end)
            pcall(function() game:GetService("Workspace")["Tycoon"..i].Purchases.LemonX.Buttons.Multiplier["Space Agriculture"]:InvokeServer() end)
            pcall(function() game:GetService("Workspace")["Tycoon"..i].Purchases.LemonX.Buttons.Multiplier["Warp Speed Shipping"]:InvokeServer() end)
            pcall(function() game:GetService("Workspace")["Tycoon"..i].Purchases.LemonX.Buttons.Multiplier["X Exterior Signs"]:InvokeServer() end)
            pcall(function() game:GetService("Workspace")["Tycoon"..i].Purchases.LemonX.Buttons.Structure["X Rear Platform 2"]:InvokeServer() end)
            pcall(function() game:GetService("Workspace")["Tycoon"..i].Purchases.LemonX.Buttons.Structure["X Rear Platform 4"]:InvokeServer() end)
            pcall(function() game:GetService("Workspace")["Tycoon"..i].Purchases.LemonX.Buttons.Structure["X Rear Platform 5"]:InvokeServer() end)
            pcall(function() game:GetService("Workspace")["Tycoon"..i].Purchases.LemonX.Buttons.Structure["X Wall Base"]:InvokeServer() end)
            pcall(function() game:GetService("Workspace")["Tycoon"..i].Purchases.LemonX.Buttons.Structure["X Walls 2"]:InvokeServer() end)
            pcall(function() game:GetService("Workspace")["Tycoon"..i].Purchases.Minigames.Buttons["Minigame Trade"]:InvokeServer() end)
            pcall(function() game:GetService("Workspace")["Tycoon"..i].Purchases.Staircase.Buttons.Decor["Staircase Step 1"]:InvokeServer() end)
            pcall(function() game:GetService("Workspace")["Tycoon"..i].Purchases.Staircase.Buttons.Decor["Staircase Step 2"]:InvokeServer() end)
            pcall(function() game:GetService("Workspace")["Tycoon"..i].Purchases.Staircase.Buttons.Decor["Staircase Step 5"]:InvokeServer() end)
            pcall(function() game:GetService("Workspace")["Tycoon"..i].Purchases.Staircase.Buttons.Decor["Staircase Step 8"]:InvokeServer() end)
            pcall(function() game:GetService("Workspace")["Tycoon"..i].Purchases.Staircase.Buttons.Multiplier["Depot Statue Major"]:InvokeServer() end)
            pcall(function() game:GetService("Workspace")["Tycoon"..i].Purchases.Staircase.Buttons.Multiplier["Depot Statue Minor 1"]:InvokeServer() end)
            pcall(function() game:GetService("Workspace")["Tycoon"..i].Purchases.Staircase.Buttons.Multiplier["Republic Statue Major"]:InvokeServer() end)
            pcall(function() game:GetService("Workspace")["Tycoon"..i].Purchases.Staircase.Buttons.Multiplier["Republic Statue Minor 2"]:InvokeServer() end)
            pcall(function() game:GetService("Workspace")["Tycoon"..i].Purchases.Staircase.Buttons.Multiplier["Robotics Statue Minor 2"]:InvokeServer() end)
            pcall(function() game:GetService("Workspace")["Tycoon"..i].Purchases.Staircase.Buttons.Multiplier["Stand Statue Major"]:InvokeServer() end)
            pcall(function() game:GetService("Workspace")["Tycoon"..i].Purchases.Staircase.Buttons.Multiplier["Stand Statue Minor 2"]:InvokeServer() end)
            pcall(function() game:GetService("Workspace")["Tycoon"..i].Purchases.Staircase.Buttons.Multiplier["Trading Statue Major"]:InvokeServer() end)
            pcall(function() game:GetService("Workspace")["Tycoon"..i].Purchases.Staircase.Buttons.Multiplier["Trading Statue Minor 1"]:InvokeServer() end)
            pcall(function() game:GetService("Workspace")["Tycoon"..i].Purchases.Staircase.Buttons.Structure["Staircase Curve 1"]:InvokeServer() end)
            pcall(function() game:GetService("Workspace")["Tycoon"..i].Purchases.Staircase.Buttons.Structure["Staircase Curve 2"]:InvokeServer() end)
            pcall(function() game:GetService("Workspace")["Tycoon"..i].Purchases.Staircase.Buttons.Structure["Staircase Curve 3"]:InvokeServer() end)
            pcall(function() game:GetService("Workspace")["Tycoon"..i].Purchases.Staircase.Buttons.Structure["Staircase Curve 6"]:InvokeServer() end)
            pcall(function() game:GetService("Workspace")["Tycoon"..i].Purchases.Staircase.Buttons.Structure["Staircase Curve 7"]:InvokeServer() end)
            pcall(function() game:GetService("Workspace")["Tycoon"..i].Purchases.Staircase.Buttons.Structure["Staircase Curve 8"]:InvokeServer() end)
            pcall(function() game:GetService("Workspace")["Tycoon"..i].Purchases.Staircase.Buttons.Structure["Staircase Intro"]:InvokeServer() end)
            pcall(function() game:GetService("Workspace")["Tycoon"..i].Purchases.Staircase.Buttons.Structure["Staircase Platform 4"]:InvokeServer() end)
            pcall(function() game:GetService("Workspace")["Tycoon"..i].Purchases.Staircase.Buttons.Structure["Staircase Platform 7"]:InvokeServer() end)
            pcall(function() game:GetService("Workspace")["Tycoon"..i].Purchases.Staircase.Buttons.Structure["Staircase Platform Final"]:InvokeServer() end)
            pcall(function() game:GetService("Workspace")["Tycoon"..i].Purchases["Lemon Depot"].Buttons.Decor["Depot Cars"]:InvokeServer() end)
            pcall(function() game:GetService("Workspace")["Tycoon"..i].Purchases["Lemon Depot"].Buttons.Decor["Depot Ceiling Lights"]:InvokeServer() end)
            pcall(function() game:GetService("Workspace")["Tycoon"..i].Purchases["Lemon Depot"].Buttons.Decor["Depot Exterior Ladder"]:InvokeServer() end)
            pcall(function() game:GetService("Workspace")["Tycoon"..i].Purchases["Lemon Depot"].Buttons.Decor["Depot Fence"]:InvokeServer() end)
            pcall(function() game:GetService("Workspace")["Tycoon"..i].Purchases["Lemon Depot"].Buttons.Decor["Depot Garage Door 2"]:InvokeServer() end)
            pcall(function() game:GetService("Workspace")["Tycoon"..i].Purchases["Lemon Depot"].Buttons.Decor["Depot Office Lights"]:InvokeServer() end)
            pcall(function() game:GetService("Workspace")["Tycoon"..i].Purchases["Lemon Depot"].Buttons.Decor["Depot Office Plants"]:InvokeServer() end)
            pcall(function() game:GetService("Workspace")["Tycoon"..i].Purchases["Lemon Depot"].Buttons.Decor["Depot Roof"]:InvokeServer() end)
            pcall(function() game:GetService("Workspace")["Tycoon"..i].Purchases["Lemon Depot"].Buttons.Decor["Depot Sign 1"]:InvokeServer() end)
            pcall(function() game:GetService("Workspace")["Tycoon"..i].Purchases["Lemon Depot"].Buttons.Decor["Depot Sign 2"]:InvokeServer() end)
            pcall(function() game:GetService("Workspace")["Tycoon"..i].Purchases["Lemon Depot"].Buttons.Decor["Depot Speed Bump 2"]:InvokeServer() end)
            pcall(function() game:GetService("Workspace")["Tycoon"..i].Purchases["Lemon Depot"].Buttons.Decor["Depot Walls 1"]:InvokeServer() end)
            pcall(function() game:GetService("Workspace")["Tycoon"..i].Purchases["Lemon Depot"].Buttons.Multiplier.Turbochargers:InvokeServer() end)
            pcall(function() game:GetService("Workspace")["Tycoon"..i].Purchases["Lemon Depot"].Buttons.Multiplier["Bigger Fleet"]:InvokeServer() end)
            pcall(function() game:GetService("Workspace")["Tycoon"..i].Purchases["Lemon Depot"].Buttons.Multiplier["Citrus Fuel Lines"]:InvokeServer() end)
            pcall(function() game:GetService("Workspace")["Tycoon"..i].Purchases["Lemon Depot"].Buttons.Multiplier["Even Bigger Fleet"]:InvokeServer() end)
            pcall(function() game:GetService("Workspace")["Tycoon"..i].Purchases["Lemon Depot"].Buttons.Multiplier["Lemon Commercials"]:InvokeServer() end)
            pcall(function() game:GetService("Workspace")["Tycoon"..i].Purchases["Lemon Depot"].Buttons.Multiplier["Toll Evasion"]:InvokeServer() end)
            pcall(function() game:GetService("Workspace")["Tycoon"..i].Purchases["Lemon Depot"].Buttons.Multiplier["Truck Branding"]:InvokeServer() end)
            pcall(function() game:GetService("Workspace")["Tycoon"..i].Purchases["Lemon Depot"].Buttons.Multiplier["Wholesale Pricing"]:InvokeServer() end)
            pcall(function() game:GetService("Workspace")["Tycoon"..i].Purchases["Lemon Depot"].Buttons.Structure["Depot Foundation"]:InvokeServer() end)
            pcall(function() game:GetService("Workspace")["Tycoon"..i].Purchases["Lemon Depot"].Buttons.Structure["Depot Office Floor"]:InvokeServer() end)
            pcall(function() game:GetService("Workspace")["Tycoon"..i].Purchases["Lemon Depot"].Buttons.Structure["Depot Raised Area"]:InvokeServer() end)
            pcall(function() game:GetService("Workspace")["Tycoon"..i].Purchases["Lemon Depot"].Buttons.Structure["Depot Roof Framing"]:InvokeServer() end)
            pcall(function() game:GetService("Workspace")["Tycoon"..i].Purchases["Lemon Labs"].Buttons.Decor["Labs Cars"]:InvokeServer() end)
            pcall(function() game:GetService("Workspace")["Tycoon"..i].Purchases["Lemon Labs"].Buttons.Decor["Labs Entry Plants"]:InvokeServer() end)
            pcall(function() game:GetService("Workspace")["Tycoon"..i].Purchases["Lemon Labs"].Buttons.Decor["Labs Entry"]:InvokeServer() end)
            pcall(function() game:GetService("Workspace")["Tycoon"..i].Purchases["Lemon Labs"].Buttons.Decor["Labs Lounge Area"]:InvokeServer() end)
            pcall(function() game:GetService("Workspace")["Tycoon"..i].Purchases["Lemon Labs"].Buttons.Decor["Labs Lower Lights"]:InvokeServer() end)
            pcall(function() game:GetService("Workspace")["Tycoon"..i].Purchases["Lemon Labs"].Buttons.Decor["Labs Roof Door"]:InvokeServer() end)
            pcall(function() game:GetService("Workspace")["Tycoon"..i].Purchases["Lemon Labs"].Buttons.Decor["Labs Room 2 Door"]:InvokeServer() end)
            pcall(function() game:GetService("Workspace")["Tycoon"..i].Purchases["Lemon Labs"].Buttons.Decor["Labs Room 3 Door"]:InvokeServer() end)
            pcall(function() game:GetService("Workspace")["Tycoon"..i].Purchases["Lemon Labs"].Buttons.Decor["Labs Second Floor Lights"]:InvokeServer() end)
            pcall(function() game:GetService("Workspace")["Tycoon"..i].Purchases["Lemon Labs"].Buttons.Decor["Labs Second Floor Windows"]:InvokeServer() end)
            pcall(function() game:GetService("Workspace")["Tycoon"..i].Purchases["Lemon Labs"].Buttons.Decor["Labs Windows"]:InvokeServer() end)
            pcall(function() game:GetService("Workspace")["Tycoon"..i].Purchases["Lemon Labs"].Buttons.Multipliers["Citrus Based Fuel"]:InvokeServer() end)
            pcall(function() game:GetService("Workspace")["Tycoon"..i].Purchases["Lemon Labs"].Buttons.Multipliers["Climate Control"]:InvokeServer() end)
            pcall(function() game:GetService("Workspace")["Tycoon"..i].Purchases["Lemon Labs"].Buttons.Multipliers["Fuel Deliveries"]:InvokeServer() end)
            pcall(function() game:GetService("Workspace")["Tycoon"..i].Purchases["Lemon Labs"].Buttons.Multipliers["Labs Exterior Sign"]:InvokeServer() end)
            pcall(function() game:GetService("Workspace")["Tycoon"..i].Purchases["Lemon Labs"].Buttons.Multipliers["Lemon Reactor"]:InvokeServer() end)
            pcall(function() game:GetService("Workspace")["Tycoon"..i].Purchases["Lemon Labs"].Buttons.Multipliers["Nano Tech"]:InvokeServer() end)
            pcall(function() game:GetService("Workspace")["Tycoon"..i].Purchases["Lemon Labs"].Buttons.Structure["Labs Balcony"]:InvokeServer() end)
            pcall(function() game:GetService("Workspace")["Tycoon"..i].Purchases["Lemon Labs"].Buttons.Structure["Labs Ladder"]:InvokeServer() end)
            pcall(function() game:GetService("Workspace")["Tycoon"..i].Purchases["Lemon Labs"].Buttons.Structure["Labs Room 3"]:InvokeServer() end)
            pcall(function() game:GetService("Workspace")["Tycoon"..i].Purchases["Lemon Labs"].Buttons.Structure["Labs Testing Area"]:InvokeServer() end)
            pcall(function() game:GetService("Workspace")["Tycoon"..i].Purchases["Lemon Labs"].Buttons.Structure["Labs Walls 1"]:InvokeServer() end)
            pcall(function() game:GetService("Workspace")["Tycoon"..i].Purchases["Lemon Labs"].Buttons.Structure["Labs Walls 2"]:InvokeServer() end)
            pcall(function() game:GetService("Workspace")["Tycoon"..i].Purchases["Lemon Labs"].Buttons.Structure["Labs Walls Detailing"]:InvokeServer() end)
            pcall(function() game:GetService("Workspace")["Tycoon"..i].Purchases["Lemon Republic"].Buttons.Decor["Republic Balcony Door"]:InvokeServer() end)
            pcall(function() game:GetService("Workspace")["Tycoon"..i].Purchases["Lemon Republic"].Buttons.Decor["Republic Curbs"]:InvokeServer() end)
            pcall(function() game:GetService("Workspace")["Tycoon"..i].Purchases["Lemon Republic"].Buttons.Decor["Republic Floor 1 Plants"]:InvokeServer() end)
            pcall(function() game:GetService("Workspace")["Tycoon"..i].Purchases["Lemon Republic"].Buttons.Decor["Republic Floor 2 Lighting"]:InvokeServer() end)
            pcall(function() game:GetService("Workspace")["Tycoon"..i].Purchases["Lemon Republic"].Buttons.Decor["Republic Floor 2 Plants 1"]:InvokeServer() end)
            pcall(function() game:GetService("Workspace")["Tycoon"..i].Purchases["Lemon Republic"].Buttons.Decor["Republic Floor 2 Windows"]:InvokeServer() end)
            pcall(function() game:GetService("Workspace")["Tycoon"..i].Purchases["Lemon Republic"].Buttons.Decor["Republic Floor 3 Lighting"]:InvokeServer() end)
            pcall(function() game:GetService("Workspace")["Tycoon"..i].Purchases["Lemon Republic"].Buttons.Decor["Republic Floor 3 Staircase 2"]:InvokeServer() end)
            pcall(function() game:GetService("Workspace")["Tycoon"..i].Purchases["Lemon Republic"].Buttons.Decor["Republic Greenery 1"]:InvokeServer() end)
            pcall(function() game:GetService("Workspace")["Tycoon"..i].Purchases["Lemon Republic"].Buttons.Decor["Republic Inner Statue 1"]:InvokeServer() end)
            pcall(function() game:GetService("Workspace")["Tycoon"..i].Purchases["Lemon Republic"].Buttons.Decor["Republic Inner Statue 2"]:InvokeServer() end)
            pcall(function() game:GetService("Workspace")["Tycoon"..i].Purchases["Lemon Republic"].Buttons.Decor["Republic Painting 1"]:InvokeServer() end)
            pcall(function() game:GetService("Workspace")["Tycoon"..i].Purchases["Lemon Republic"].Buttons.Decor["Republic Parked Cars"]:InvokeServer() end)
            pcall(function() game:GetService("Workspace")["Tycoon"..i].Purchases["Lemon Republic"].Buttons.Decor["Republic Red Carpet"]:InvokeServer() end)
            pcall(function() game:GetService("Workspace")["Tycoon"..i].Purchases["Lemon Republic"].Buttons.Decor["Republic Skylight"]:InvokeServer() end)
            pcall(function() game:GetService("Workspace")["Tycoon"..i].Purchases["Lemon Republic"].Buttons.Decor["Republic Welcome Sign"]:InvokeServer() end)
            pcall(function() game:GetService("Workspace")["Tycoon"..i].Purchases["Lemon Republic"].Buttons.Multiplier["Bank Expansion"]:InvokeServer() end)
            pcall(function() game:GetService("Workspace")["Tycoon"..i].Purchases["Lemon Republic"].Buttons.Multiplier["Centralized Power"]:InvokeServer() end)
            pcall(function() game:GetService("Workspace")["Tycoon"..i].Purchases["Lemon Republic"].Buttons.Multiplier["Lemon Propaganda"]:InvokeServer() end)
            pcall(function() game:GetService("Workspace")["Tycoon"..i].Purchases["Lemon Republic"].Buttons.Multiplier["Lemon Subsidies"]:InvokeServer() end)
            pcall(function() game:GetService("Workspace")["Tycoon"..i].Purchases["Lemon Republic"].Buttons.Multiplier["Lemon Tariffs"]:InvokeServer() end)
            pcall(function() game:GetService("Workspace")["Tycoon"..i].Purchases["Lemon Republic"].Buttons.Multiplier["Lemon Tax"]:InvokeServer() end)
            pcall(function() game:GetService("Workspace")["Tycoon"..i].Purchases["Lemon Republic"].Buttons.Multiplier["Personal Aides"]:InvokeServer() end)
            pcall(function() game:GetService("Workspace")["Tycoon"..i].Purchases["Lemon Republic"].Buttons.Multiplier["Public Citrus Works"]:InvokeServer() end)
            pcall(function() game:GetService("Workspace")["Tycoon"..i].Purchases["Lemon Republic"].Buttons.Multiplier["Reduced Regulation"]:InvokeServer() end)
            pcall(function() game:GetService("Workspace")["Tycoon"..i].Purchases["Lemon Republic"].Buttons.Other["Republic Manager"]:InvokeServer() end)
            pcall(function() game:GetService("Workspace")["Tycoon"..i].Purchases["Lemon Republic"].Buttons.Structure["Republic Balcony"]:InvokeServer() end)
            pcall(function() game:GetService("Workspace")["Tycoon"..i].Purchases["Lemon Republic"].Buttons.Structure["Republic Building 1"]:InvokeServer() end)
            pcall(function() game:GetService("Workspace")["Tycoon"..i].Purchases["Lemon Republic"].Buttons.Structure["Republic Building 2"]:InvokeServer() end)
            pcall(function() game:GetService("Workspace")["Tycoon"..i].Purchases["Lemon Republic"].Buttons.Structure["Republic Courtyard"]:InvokeServer() end)
            pcall(function() game:GetService("Workspace")["Tycoon"..i].Purchases["Lemon Republic"].Buttons.Structure["Republic Floor 2 Left"]:InvokeServer() end)
            pcall(function() game:GetService("Workspace")["Tycoon"..i].Purchases["Lemon Republic"].Buttons.Structure["Republic Floor 2 Staircase 1"]:InvokeServer() end)
            pcall(function() game:GetService("Workspace")["Tycoon"..i].Purchases["Lemon Republic"].Buttons.Structure["Republic Floor 2 Walls"]:InvokeServer() end)
            pcall(function() game:GetService("Workspace")["Tycoon"..i].Purchases["Lemon Republic"].Buttons.Structure["Republic Floor 3 Walls"]:InvokeServer() end)
            pcall(function() game:GetService("Workspace")["Tycoon"..i].Purchases["Lemon Republic"].Buttons.Structure["Republic Floor 3"]:InvokeServer() end)
            pcall(function() game:GetService("Workspace")["Tycoon"..i].Purchases["Lemon Republic"].Buttons.Structure["Republic Front Pillars 1"]:InvokeServer() end)
            pcall(function() game:GetService("Workspace")["Tycoon"..i].Purchases["Lemon Republic"].Buttons.Structure["Republic Rear Pillar 1"]:InvokeServer() end)
            pcall(function() game:GetService("Workspace")["Tycoon"..i].Purchases["Lemon Republic"].Buttons.Structure["Republic Rear Pillar 2"]:InvokeServer() end)
            pcall(function() game:GetService("Workspace")["Tycoon"..i].Purchases["Lemon Republic"].Buttons.Structure["Republic Roof"]:InvokeServer() end)
            pcall(function() game:GetService("Workspace")["Tycoon"..i].Purchases["Lemon Republic"].Buttons["Lemon Republic"]:InvokeServer() end)
            pcall(function() game:GetService("Workspace")["Tycoon"..i].Purchases["Lemon Robotics"].Buttons.Decor["Robotics Cars"]:InvokeServer() end)
            pcall(function() game:GetService("Workspace")["Tycoon"..i].Purchases["Lemon Robotics"].Buttons.Decor["Robotics Curbs 1"]:InvokeServer() end)
            pcall(function() game:GetService("Workspace")["Tycoon"..i].Purchases["Lemon Robotics"].Buttons.Decor["Robotics Curbs 2"]:InvokeServer() end)
            pcall(function() game:GetService("Workspace")["Tycoon"..i].Purchases["Lemon Robotics"].Buttons.Decor["Robotics Curbs 3"]:InvokeServer() end)
            pcall(function() game:GetService("Workspace")["Tycoon"..i].Purchases["Lemon Robotics"].Buttons.Decor["Robotics Entry Lighting"]:InvokeServer() end)
            pcall(function() game:GetService("Workspace")["Tycoon"..i].Purchases["Lemon Robotics"].Buttons.Decor["Robotics Greenery 1"]:InvokeServer() end)
            pcall(function() game:GetService("Workspace")["Tycoon"..i].Purchases["Lemon Robotics"].Buttons.Decor["Robotics Greenery 2"]:InvokeServer() end)
            pcall(function() game:GetService("Workspace")["Tycoon"..i].Purchases["Lemon Robotics"].Buttons.Decor["Robotics Lighting 1"]:InvokeServer() end)
            pcall(function() game:GetService("Workspace")["Tycoon"..i].Purchases["Lemon Robotics"].Buttons.Decor["Robotics Mega Door"]:InvokeServer() end)
            pcall(function() game:GetService("Workspace")["Tycoon"..i].Purchases["Lemon Robotics"].Buttons.Decor["Robotics Parking Lot"]:InvokeServer() end)
            pcall(function() game:GetService("Workspace")["Tycoon"..i].Purchases["Lemon Robotics"].Buttons.Decor["Robotics Railings 1"]:InvokeServer() end)
            pcall(function() game:GetService("Workspace")["Tycoon"..i].Purchases["Lemon Robotics"].Buttons.Decor["Robotics Railings 3"]:InvokeServer() end)
            pcall(function() game:GetService("Workspace")["Tycoon"..i].Purchases["Lemon Robotics"].Buttons.Decor["Robotics Staircase 2"]:InvokeServer() end)
            pcall(function() game:GetService("Workspace")["Tycoon"..i].Purchases["Lemon Robotics"].Buttons.Multiplier["Citrus Lubricant"]:InvokeServer() end)
            pcall(function() game:GetService("Workspace")["Tycoon"..i].Purchases["Lemon Robotics"].Buttons.Multiplier["Cyber Lemons"]:InvokeServer() end)
            pcall(function() game:GetService("Workspace")["Tycoon"..i].Purchases["Lemon Robotics"].Buttons.Multiplier["Lemon Domination"]:InvokeServer() end)
            pcall(function() game:GetService("Workspace")["Tycoon"..i].Purchases["Lemon Robotics"].Buttons.Multiplier["Military Contracts"]:InvokeServer() end)
            pcall(function() game:GetService("Workspace")["Tycoon"..i].Purchases["Lemon Robotics"].Buttons.Multiplier["Nanobot Farm"]:InvokeServer() end)
            pcall(function() game:GetService("Workspace")["Tycoon"..i].Purchases["Lemon Robotics"].Buttons.Multiplier["Overseas Production"]:InvokeServer() end)
            pcall(function() game:GetService("Workspace")["Tycoon"..i].Purchases["Lemon Robotics"].Buttons.Multiplier["Robot Employees"]:InvokeServer() end)
            pcall(function() game:GetService("Workspace")["Tycoon"..i].Purchases["Lemon Robotics"].Buttons.Multiplier["Robot Overclocking"]:InvokeServer() end)
            pcall(function() game:GetService("Workspace")["Tycoon"..i].Purchases["Lemon Robotics"].Buttons.Multiplier["Robotics Exterior Signs"]:InvokeServer() end)
            pcall(function() game:GetService("Workspace")["Tycoon"..i].Purchases["Lemon Robotics"].Buttons.Structure["Robotics Balcony 1"]:InvokeServer() end)
            pcall(function() game:GetService("Workspace")["Tycoon"..i].Purchases["Lemon Robotics"].Buttons.Structure["Robotics Balcony 2"]:InvokeServer() end)
            pcall(function() game:GetService("Workspace")["Tycoon"..i].Purchases["Lemon Stand"].Buttons.Multiplier["Ice Maker"]:InvokeServer() end)
            pcall(function() game:GetService("Workspace")["Tycoon"..i].Purchases["Lemon Stand"].Buttons.Multiplier["Street Fliers"]:InvokeServer() end)
            pcall(function() game:GetService("Workspace")["Tycoon"..i].Purchases["Lemon Stand"].Buttons.Multiplier["Sugar Mixer"]:InvokeServer() end)
            pcall(function() game:GetService("Workspace")["Tycoon"..i].Purchases["Lemon Stand"].Buttons["Lemon Stand"]:InvokeServer() end)
            pcall(function() game:GetService("Workspace")["Tycoon"..i].Purchases["Lemon Trading"].Buttons.Decor["Trading Floor 1 Lights"]:InvokeServer() end)
            pcall(function() game:GetService("Workspace")["Tycoon"..i].Purchases["Lemon Trading"].Buttons.Decor["Trading Floor 1 Windows"]:InvokeServer() end)
            pcall(function() game:GetService("Workspace")["Tycoon"..i].Purchases["Lemon Trading"].Buttons.Decor["Trading Floor 2 Windows"]:InvokeServer() end)
            pcall(function() game:GetService("Workspace")["Tycoon"..i].Purchases["Lemon Trading"].Buttons.Decor["Trading Floor 3 Windows"]:InvokeServer() end)
            pcall(function() game:GetService("Workspace")["Tycoon"..i].Purchases["Lemon Trading"].Buttons.Decor["Trading Greenery"]:InvokeServer() end)
            pcall(function() game:GetService("Workspace")["Tycoon"..i].Purchases["Lemon Trading"].Buttons.Decor["Trading Roof"]:InvokeServer() end)
            pcall(function() game:GetService("Workspace")["Tycoon"..i].Purchases["Lemon Trading"].Buttons.Decor["Trading Sign"]:InvokeServer() end)
            pcall(function() game:GetService("Workspace")["Tycoon"..i].Purchases["Lemon Trading"].Buttons.Multiplier["24 Hour Trading"]:InvokeServer() end)
            pcall(function() game:GetService("Workspace")["Tycoon"..i].Purchases["Lemon Trading"].Buttons.Multiplier["Go Public"]:InvokeServer() end)
            pcall(function() game:GetService("Workspace")["Tycoon"..i].Purchases["Lemon Trading"].Buttons.Multiplier["Lemon NFTs"]:InvokeServer() end)
            pcall(function() game:GetService("Workspace")["Tycoon"..i].Purchases["Lemon Trading"].Buttons.Multiplier["Obfuscated Finances"]:InvokeServer() end)
            pcall(function() game:GetService("Workspace")["Tycoon"..i].Purchases["Lemon Trading"].Buttons.Multiplier["Offshore Banking"]:InvokeServer() end)
            pcall(function() game:GetService("Workspace")["Tycoon"..i].Purchases["Lemon Trading"].Buttons.Multiplier["Trading Exterior Displays"]:InvokeServer() end)
            pcall(function() game:GetService("Workspace")["Tycoon"..i].Purchases["Lemon Trading"].Buttons.Other["Trading Manager"]:InvokeServer() end)
            pcall(function() game:GetService("Workspace")["Tycoon"..i].Purchases["Lemon Trading"].Buttons.Structure["Trading Lot"]:InvokeServer() end)
            pcall(function() game:GetService("Workspace")["Tycoon"..i].Purchases["Lemon Trading"].Buttons.Structure["Trading Roof Supports"]:InvokeServer() end)
            pcall(function() game:GetService("Workspace")["Tycoon"..i].Purchases["Lemon Trading"].Buttons["Lemon Trading"]:InvokeServer() end)
            pcall(function() game:GetService("Workspace")["Tycoon"..i].Purchases["LemonX Ground"].Buttons.Decor["X Fence 2"]:InvokeServer() end)
            pcall(function() game:GetService("Workspace")["Tycoon"..i].Purchases["LemonX Ground"].Buttons.Decor["X Fence 3"]:InvokeServer() end)
            pcall(function() game:GetService("Workspace")["Tycoon"..i].Purchases["LemonX Ground"].Buttons.Decor["X Gate Barrier Arm"]:InvokeServer() end)
            pcall(function() game:GetService("Workspace")["Tycoon"..i].Purchases["LemonX Ground"].Buttons.Decor["X Ground Containers 1"]:InvokeServer() end)
            pcall(function() game:GetService("Workspace")["Tycoon"..i].Purchases["LemonX Ground"].Buttons.Decor["X Ground Containers 2"]:InvokeServer() end)
            pcall(function() game:GetService("Workspace")["Tycoon"..i].Purchases["LemonX Ground"].Buttons.Decor["X Ground Containers 3"]:InvokeServer() end)
            pcall(function() game:GetService("Workspace")["Tycoon"..i].Purchases["LemonX Ground"].Buttons.Decor["X Loose Scaffolding"]:InvokeServer() end)
            pcall(function() game:GetService("Workspace")["Tycoon"..i].Purchases["LemonX Ground"].Buttons.Decor["X Road Curbs"]:InvokeServer() end)
            pcall(function() game:GetService("Workspace")["Tycoon"..i].Purchases["LemonX Ground"].Buttons.Decor["X Truck 1"]:InvokeServer() end)
            pcall(function() game:GetService("Workspace")["Tycoon"..i].Purchases["LemonX Ground"].Buttons.Decor["X Truck 2"]:InvokeServer() end)
            pcall(function() game:GetService("Workspace")["Tycoon"..i].Purchases["LemonX Ground"].Buttons.Decor["X Van"]:InvokeServer() end)
            pcall(function() game:GetService("Workspace")["Tycoon"..i].Purchases["LemonX Ground"].Buttons.Structure["X Control Lights"]:InvokeServer() end)
            pcall(function() game:GetService("Workspace")["Tycoon"..i].Purchases["LemonX Ground"].Buttons.Structure["X Launch Surface"]:InvokeServer() end)
            pcall(function() game:GetService("Workspace")["Tycoon"..i].Purchases["LemonX Ground"].Buttons.Structure["X Launchpad"]:InvokeServer() end)
            pcall(function() game:GetService("Workspace")["Tycoon"..i].Purchases["LemonX Ground"].Buttons.Structure["X Rocket Lift"]:InvokeServer() end)
            pcall(function() game:GetService("Workspace")["Tycoon"..i].Purchases["LemonX Ground"].Buttons.Structure["X Scaffolding 2"]:InvokeServer() end)
            pcall(function() game:GetService("Workspace")["Tycoon"..i].Purchases["LemonX Ground"].Buttons.Structure["X Scaffolding 3"]:InvokeServer() end)
                task.wait(0.05)
            end
            Rayfield:Notify({
                Title = "Selesai!",
                Content = "Semua purchase Tycoon 1-50 berhasil!",
                Duration = 5,
            })
        end)
    end,
})
